### ISSUE TITLE
Many of these facilities already covered by other libraries

### ISSUE THREAD

**Issue by svetlyak40wt** [inaimathi/clj#1]
A few of the libraries you might consider to reuse:

1. rutils [rationale](https://github.com/vseloved/rutils/blob/master/docs/ann-rutils.md), [tutorial](https://github.com/vseloved/rutils/blob/master/docs/ann-rutils.md), [anaphoric](https://github.com/vseloved/rutils/blob/master/core/anaphora.lisp), [syntax](https://github.com/vseloved/rutils/blob/master/core/readtable.lisp), [arrows](https://github.com/vseloved/rutils/blob/master/core/misc.lisp#L325), [named-lambda/fn](https://github.com/vseloved/rutils/blob/4ea1e89543db19030c26b344e0f8d35d5349235d/core/misc.lisp#L89)
2. arrows [documentaion](https://gitlab.com/Harleqin/arrows)

**Comment by inaimathi** [comment]
Arrows has been imported and exposed as part of the interface. `rutils` has significant aim differences from this library. Specifically

1. It seems to have the goal of being expansive, replacing or supplementing something like `alexandria`. `clj` aims to be fairly minimal, with additional libraries potentially built with it.
2. It designates convenient, clojure-ish syntax for mutable data structures. `clj` aims to be functional and immutable (more in line with the `clojure` approach)
